allowBuilds:
  esbuild: true
  sqlite3: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@rsbuild/core@2.0.8'
  - '@rspack/binding-darwin-arm64@2.0.5'
  - '@rspack/binding-darwin-x64@2.0.5'
  - '@rspack/binding-linux-arm64-gnu@2.0.5'
  - '@rspack/binding-linux-arm64-musl@2.0.5'
  - '@rspack/binding-linux-x64-gnu@2.0.5'
  - '@rspack/binding-linux-x64-musl@2.0.5'
  - '@rspack/binding-wasm32-wasi@2.0.5'
  - '@rspack/binding-win32-arm64-msvc@2.0.5'
  - '@rspack/binding-win32-ia32-msvc@2.0.5'
  - '@rspack/binding-win32-x64-msvc@2.0.5'
  - '@rspack/binding@2.0.5'
  - '@rspack/core@2.0.5'
  - openai@6.39.1
